player:
  autodetect: true

log_parsing:
  enabled: true
  cycle_on_start: false

guild_tracking:
  enabled: true
  discord_output:
    events:
      - JOIN_GUILD
      - LEAVE_GUILD
      - OPENDKP_OFF_DUTY
  interval: 300
  opendkp_metrics:
    off_duty:
      key: calculated_30
      threshold: .40

opendkp:
  enabled: true
  host: fanotest.opendkp.com
  aws_region: us-east-2
  root_endpoint: https://7gnjtigho4.execute-api.us-east-2.amazonaws.com/beta
  identity_endpoint: https://4jmtrkwc86.execute-api.us-east-2.amazonaws.com/beta
  secure_endpoint: https://orgl2496uk.execute-api.us-east-2.amazonaws.com/beta

dkp:
  bidding:
    enabled: true
    restrict_to_guildies: false

game:
  root_folder: C:\Program Files (x86)\Steam\steamapps\common\Everquest F2P

buffing:
  enabled: true
  restrict_to_guildies: true
  spells:
    Voice of Clarivoyance:
      spell_slot: 6
      cast_time: 12
    Hastening of Salik:
      spell_slot: 7
      cast_time: 9
